In [ ]:
!pip install numpy pandas opendatasets scikit-learn xgboost --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 kB 1.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for uuid (setup.py) ... done

In [ ]:
import pandas as pd

In [ ]:

import opendatasets as od

In [ ]:
dataset_url = 'https://www.kaggle.com/datasets/sobhanmoosavi/us-accidents'

In [ ]:
od.download(dataset_url)

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: elli31
Your Kaggle Key: ··········
Downloading us-accidents.zip to ./us-accidents

100%|██████████| 653M/653M [00:23<00:00, 29.5MB/s]

In [ ]:
data_dir = 'us-accidents'

In [ ]:

import os
os.listdir(data_dir)

['US_Accidents_March23.csv']

In [ ]:

!wc -l {data_dir}/US_Accidents_March23.csv

7728395 us-accidents/US_Accidents_March23.csv

In [ ]:

file_name = 'us-accidents/US_Accidents_March23.csv'

chunk_size = 100000

chunks = []

for chunk in pd.read_csv(file_name,chunksize=chunk_size):
    chunks.append(chunk)

df = pd.concat(chunks)

In [ ]:
import numpy as np

In [ ]:
df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.01,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.01,...,False,False,False,False,True,False,Day,Day,Day,Day

In [ ]:
df.shape

(7728394, 46)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 46 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Source                 object
 2   Severity               int64
 3   Start_Time             object
 4   End_Time               object
 5   Start_Lat              float64
 6   Start_Lng              float64
 7   End_Lat                float64
 8   End_Lng                float64
 9   Distance(mi)           float64
 10  Description            object
 11  Street                 object
 12  City                   object
 13  County                 object
 14  State                  object
 15  Zipcode                object
 16  Country                object
 17  Timezone               object
 18  Airport_Code           object
 19  Weather_Timestamp      object
 20  Temperature(F)         float64
 21  Wind_Chill(F)          float64
 22  Humidity(%)            float64
 23  Pressure(in)           float64
 24  Visibility(mi)         float64
 25  Wind_Direction         object
 26  Wind_Speed(mph)        float64
 27  Precipitation(in)      float64
 28  Weather_Condition      object
 29  Amenity                bool
 30  Bump                   bool
 31  Crossing               bool
 32  Give_Way               bool
 33  Junction               bool
 34  No_Exit                bool
 35  Railway                bool
 36  Roundabout             bool
 37  Station                bool
 38  Stop                   bool
 39  Traffic_Calming        bool
 40  Traffic_Signal         bool
 41  Turning_Loop           bool
 42  Sunrise_Sunset         object
 43  Civil_Twilight         object
 44  Nautical_Twilight      object
 45  Astronomical_Twilight  object
dtypes: bool(13), float64(12), int64(1), object(20)
memory usage: 2.0+ GB

In [ ]:
df['Start_Time'] = pd.to_datetime(df['Start_Time'])
df['End_Time'] = pd.to_datetime(df['End_Time'])
df['Weather_Timestamp'] = pd.to_datetime(df['Weather_Timestamp'])

In [ ]:
categorical_columns = ['Source', 'Street', 'City', 'County', 'State', 'Zipcode', 'Country', 'Timezone', 'Airport_Code', 'Wind_Direction', 'Weather_Condition', 'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight', 'Astronomical_Twilight']

for column in categorical_columns:
    df[column] = df[column].astype('category')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 46 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Source                 category
 2   Severity               int64
 3   Start_Time             datetime64[ns]
 4   End_Time               datetime64[ns]
 5   Start_Lat              float64
 6   Start_Lng              float64
 7   End_Lat                float64
 8   End_Lng                float64
 9   Distance(mi)           float64
 10  Description            object
 11  Street                 category
 12  City                   category
 13  County                 category
 14  State                  category
 15  Zipcode                category
 16  Country                category
 17  Timezone               category
 18  Airport_Code           category
 19  Weather_Timestamp      datetime64[ns]
 20  Temperature(F)         float64
 21  Wind_Chill(F)          float64
 22  Humidity(%)            float64
 23  Pressure(in)           float64
 24  Visibility(mi)         float64
 25  Wind_Direction         category
 26  Wind_Speed(mph)        float64
 27  Precipitation(in)      float64
 28  Weather_Condition      category
 29  Amenity                bool
 30  Bump                   bool
 31  Crossing               bool
 32  Give_Way               bool
 33  Junction               bool
 34  No_Exit                bool
 35  Railway                bool
 36  Roundabout             bool
 37  Station                bool
 38  Stop                   bool
 39  Traffic_Calming        bool
 40  Traffic_Signal         bool
 41  Turning_Loop           bool
 42  Sunrise_Sunset         category
 43  Civil_Twilight         category
 44  Nautical_Twilight      category
 45  Astronomical_Twilight  category
dtypes: bool(13), category(15), datetime64[ns](3), float64(12), int64(1), object(2)
memory usage: 1.4+ GB

In [ ]:
df.isnull().sum().sort_values(ascending=False)

End_Lat                  3402762
End_Lng                  3402762
Precipitation(in)        2203586
Wind_Chill(F)            1999019
Wind_Speed(mph)           571233
Visibility(mi)            177098
Wind_Direction            175206
Humidity(%)               174144
Weather_Condition         173459
Temperature(F)            163853
Pressure(in)              140679
Weather_Timestamp         120228
Nautical_Twilight          23246
Civil_Twilight             23246
Sunrise_Sunset             23246
Astronomical_Twilight      23246
Airport_Code               22635
Street                     10869
Timezone                    7808
Zipcode                     1915
City                         253
Description                    5
Traffic_Signal                 0
Roundabout                     0
Station                        0
Stop                           0
Traffic_Calming                0
Country                        0
Turning_Loop                   0
No_Exit                        0
End_Time                       0
Start_Time                     0
Severity                       0
Railway                        0
Crossing                       0
Junction                       0
Give_Way                       0
Bump                           0
Amenity                        0
Start_Lat                      0
Start_Lng                      0
Distance(mi)                   0
Source                         0
County                         0
State                          0
ID                             0
dtype: int64

In [ ]:
numeric_columns = ['End_Lat', 'End_Lng', 'Precipitation(in)', 'Wind_Chill(F)', 'Wind_Speed(mph)', 'Visibility(mi)',
                    'Humidity(%)', 'Temperature(F)', 'Pressure(in)']
for column in numeric_columns:
    df[column].fillna(df[column].median(), inplace=True)

categorical_columns = ['Wind_Direction', 'Weather_Condition', 'Airport_Code', 'Street', 'Timezone', 'Zipcode', 'City', 'Description']
for column in categorical_columns:
    df[column].fillna(df[column].mode()[0], inplace=True)

datetime_columns = ['Weather_Timestamp', 'Nautical_Twilight', 'Civil_Twilight', 'Sunrise_Sunset', 'Astronomical_Twilight']
for column in datetime_columns:
    df[column].fillna(method='ffill', inplace=True)

In [ ]:
df.isnull()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7728389,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7728390,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7728391,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7728392,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7728393,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum().sort_values(ascending=False)

ID                       0
No_Exit                  0
Wind_Direction           0
Wind_Speed(mph)          0
Precipitation(in)        0
Weather_Condition        0
Amenity                  0
Bump                     0
Crossing                 0
Give_Way                 0
Junction                 0
Railway                  0
Source                   0
Roundabout               0
Station                  0
Stop                     0
Traffic_Calming          0
Traffic_Signal           0
Turning_Loop             0
Sunrise_Sunset           0
Civil_Twilight           0
Nautical_Twilight        0
Visibility(mi)           0
Pressure(in)             0
Humidity(%)              0
Wind_Chill(F)            0
Severity                 0
Start_Time               0
End_Time                 0
Start_Lat                0
Start_Lng                0
End_Lat                  0
End_Lng                  0
Distance(mi)             0
Description              0
Street                   0
City                     0
County                   0
State                    0
Zipcode                  0
Country                  0
Timezone                 0
Airport_Code             0
Weather_Timestamp        0
Temperature(F)           0
Astronomical_Twilight    0
dtype: int64

In [ ]:
df.head(10)

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,36.183495,-88.02789,0.01,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,36.183495,-88.02789,0.01,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,36.183495,-88.02789,0.01,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,36.183495,-88.02789,0.01,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,36.183495,-88.02789,0.01,...,False,False,False,False,True,False,Day,Day,Day,Day
5,A-6,Source2,3,2016-02-08 07:44:26,2016-02-08 08:14:26,40.100590,-82.925194,36.183495,-88.02789,0.01,...,False,False,False,False,False,False,Day,Day,Day,Day
6,A-7,Source2,2,2016-02-08 07:59:35,2016-02-08 08:29:35,39.758274,-84.230507,36.183495,-88.02789,0.00,...,False,False,False,False,False,False,Day,Day,Day,Day
7,A-8,Source2,3,2016-02-08 07:59:58,2016-02-08 08:29:58,39.770382,-84.194901,36.183495,-88.02789,0.01,...,False,False,False,False,False,False,Day,Day,Day,Day
8,A-9,Source2,2,2016-02-08 08:00:40,2016-02-08 08:30:40,39.778061,-84.172005,36.183495,-88.02789,0.00,...,False,False,False,False,False,False,Day,Day,Day,Day
9,A-10,Source2,3,2016-02-08 08:10:04,2016-02-08 08:40:04,40.100590,-82.925194,36.183495,-88.02789,0.01,...,False,False,False,False,False,False,Day,Day,Day,Day

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 46 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Source                 category
 2   Severity               int64
 3   Start_Time             datetime64[ns]
 4   End_Time               datetime64[ns]
 5   Start_Lat              float64
 6   Start_Lng              float64
 7   End_Lat                float64
 8   End_Lng                float64
 9   Distance(mi)           float64
 10  Description            object
 11  Street                 category
 12  City                   category
 13  County                 category
 14  State                  category
 15  Zipcode                category
 16  Country                category
 17  Timezone               category
 18  Airport_Code           category
 19  Weather_Timestamp      datetime64[ns]
 20  Temperature(F)         float64
 21  Wind_Chill(F)          float64
 22  Humidity(%)            float64
 23  Pressure(in)           float64
 24  Visibility(mi)         float64
 25  Wind_Direction         category
 26  Wind_Speed(mph)        float64
 27  Precipitation(in)      float64
 28  Weather_Condition      category
 29  Amenity                bool
 30  Bump                   bool
 31  Crossing               bool
 32  Give_Way               bool
 33  Junction               bool
 34  No_Exit                bool
 35  Railway                bool
 36  Roundabout             bool
 37  Station                bool
 38  Stop                   bool
 39  Traffic_Calming        bool
 40  Traffic_Signal         bool
 41  Turning_Loop           bool
 42  Sunrise_Sunset         category
 43  Civil_Twilight         category
 44  Nautical_Twilight      category
 45  Astronomical_Twilight  category
dtypes: bool(13), category(15), datetime64[ns](3), float64(12), int64(1), object(2)
memory usage: 1.4+ GB

In [ ]:
duplicates_list = []

for chunk in pd.read_csv(file_name, chunksize=chunk_size):
    chunk_duplicates = chunk[chunk.duplicated()]

    duplicates_list.append(chunk_duplicates)

all_duplicates = pd.concat(duplicates_list)

print("Duplicate Rows:")
print(all_duplicates)

Duplicate Rows:
Empty DataFrame
Columns: [ID, Source, Severity, Start_Time, End_Time, Start_Lat, Start_Lng, End_Lat, End_Lng, Distance(mi), Description, Street, City, County, State, Zipcode, Country, Timezone, Airport_Code, Weather_Timestamp, Temperature(F), Wind_Chill(F), Humidity(%), Pressure(in), Visibility(mi), Wind_Direction, Wind_Speed(mph), Precipitation(in), Weather_Condition, Amenity, Bump, Crossing, Give_Way, Junction, No_Exit, Railway, Roundabout, Station, Stop, Traffic_Calming, Traffic_Signal, Turning_Loop, Sunrise_Sunset, Civil_Twilight, Nautical_Twilight, Astronomical_Twilight]
Index: []

[0 rows x 46 columns]

In [ ]:
columns_to_keep = [
    'ID', 'Source', 'Severity', 'Start_Time', 'End_Time',
    'Start_Lat', 'Start_Lng', 'Distance(mi)', 'Description',
    'City', 'State', 'Temperature(F)', 'Weather_Condition',
    'Amenity', 'Bump', 'Crossing', 'Traffic_Signal', 'Sunrise_Sunset'
]

df_filtered = df[columns_to_keep].copy()

print(df_filtered.head())

    ID   Source  Severity          Start_Time            End_Time  Start_Lat  \
0  A-1  Source2         3 2016-02-08 05:46:00 2016-02-08 11:00:00  39.865147
1  A-2  Source2         2 2016-02-08 06:07:59 2016-02-08 06:37:59  39.928059
2  A-3  Source2         2 2016-02-08 06:49:27 2016-02-08 07:19:27  39.063148
3  A-4  Source2         3 2016-02-08 07:23:34 2016-02-08 07:53:34  39.747753
4  A-5  Source2         2 2016-02-08 07:39:07 2016-02-08 08:09:07  39.627781

   Start_Lng  Distance(mi)                                        Description  \
0 -84.058723          0.01  Right lane blocked due to accident on I-70 Eas...
1 -82.831184          0.01  Accident on Brice Rd at Tussing Rd. Expect del...
2 -84.032608          0.01  Accident on OH-32 State Route 32 Westbound at ...
3 -84.205582          0.01  Accident on I-75 Southbound at Exits 52 52B US...
4 -84.188354          0.01  Accident on McEwen Rd at OH-725 Miamisburg Cen...

           City State  Temperature(F) Weather_Condition  Amenity   Bump  \
0        Dayton    OH            36.9        Light Rain    False  False
1  Reynoldsburg    OH            37.9        Light Rain    False  False
2  Williamsburg    OH            36.0          Overcast    False  False
3        Dayton    OH            35.1     Mostly Cloudy    False  False
4        Dayton    OH            36.0     Mostly Cloudy    False  False

   Crossing  Traffic_Signal Sunrise_Sunset
0     False           False          Night
1     False           False          Night
2     False            True          Night
3     False           False          Night
4     False            True            Day

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

drive_path = '/content/drive/MyDrive/DetyreKursi/'

import os
os.makedirs(drive_path, exist_ok=True)

df_filtered.to_csv(drive_path + 'us-accidents_silver.csv', index=False)

print(f"The silver table has been saved to: {drive_path}us-accidents_silver.csv")

In [ ]:
from google.colab import drive
import pandas as pd



file_name = '/content/drive/MyDrive/DetyreKursi/us-accidents_silver.csv'
chunk_size = 100000

chunks = []

for chunk in pd.read_csv(file_name,chunksize=chunk_size):
    chunks.append(chunk)

df = pd.concat(chunks)

In [ ]:
df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Description,City,State,Temperature(F),Weather_Condition,Amenity,Bump,Crossing,Traffic_Signal,Sunrise_Sunset
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,0.01,Right lane blocked due to accident on I-70 Eas...,Dayton,OH,36.9,Light Rain,False,False,False,False,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,0.01,Accident on Brice Rd at Tussing Rd. Expect del...,Reynoldsburg,OH,37.9,Light Rain,False,False,False,False,Night
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,0.01,Accident on OH-32 State Route 32 Westbound at ...,Williamsburg,OH,36.0,Overcast,False,False,False,True,Night
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,0.01,Accident on I-75 Southbound at Exits 52 52B US...,Dayton,OH,35.1,Mostly Cloudy,False,False,False,False,Night
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,0.01,Accident on McEwen Rd at OH-725 Miamisburg Cen...,Dayton,OH,36.0,Mostly Cloudy,False,False,False,True,Day

In [ ]:

print("Info about the DataFrame:")
print(df.info())


duplicates = df[df.duplicated()]
print("\nDuplicate Rows:")
print(duplicates)


null_values = df.isnull().sum()
print("\nNull Values:")
print(null_values)

Info about the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 18 columns):
 #   Column             Dtype
---  ------             -----
 0   ID                 object
 1   Source             object
 2   Severity           int64
 3   Start_Time         object
 4   End_Time           object
 5   Start_Lat          float64
 6   Start_Lng          float64
 7   Distance(mi)       float64
 8   Description        object
 9   City               object
 10  State              object
 11  Temperature(F)     float64
 12  Weather_Condition  object
 13  Amenity            bool
 14  Bump               bool
 15  Crossing           bool
 16  Traffic_Signal     bool
 17  Sunrise_Sunset     object
dtypes: bool(4), float64(4), int64(1), object(9)
memory usage: 855.0+ MB
None

Duplicate Rows:
Empty DataFrame
Columns: [ID, Source, Severity, Start_Time, End_Time, Start_Lat, Start_Lng, Distance(mi), Description, City, State, Temperature(F), Weather_Condition, Amenity, Bump, Crossing, Traffic_Signal, Sunrise_Sunset]
Index: []

Null Values:
ID                   0
Source               0
Severity             0
Start_Time           0
End_Time             0
Start_Lat            0
Start_Lng            0
Distance(mi)         0
Description          0
City                 0
State                0
Temperature(F)       0
Weather_Condition    0
Amenity              0
Bump                 0
Crossing             0
Traffic_Signal       0
Sunrise_Sunset       0
dtype: int64

________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

_____________________________
TESTS
________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

_____________________________

In [ ]:
import os

current_directory = os.getcwd()

print("Current Working Directory:", current_directory)

Current Working Directory: /content

In [ ]:
# data_dir = '/content'

In [ ]:
# import os
# os.listdir(data_dir)

['.config', 'us-accidents', 'us-accidents_silver.csv', 'drive', 'sample_data']

In [ ]:
!wc -l /content/drive/MyDrive/DetyreKursi/us-accidents_silver.csv

7728395 /content/drive/MyDrive/DetyreKursi/us-accidents_silver.csv

OTHER TESTS

In [ ]:
import pandas as pd

# Specify the file path
file_path = '/content/drive/MyDrive/DetyreKursi/us-accidents_silver.csv'

# Read the CSV file
dfff = pd.read_csv(file_path)

# Convert 'Start_Time' to datetime
dfff['Start_Time'] = pd.to_datetime(dfff['Start_Time'], format='%Y-%m-%d %H:%M:%S')

# Save the changes to the same CSV file
dfff.to_csv(file_path, index=False)

# Display the head of the updated DataFrame
print("Head of the Updated DataFrame:")
print(dfff.head())

Head of the Updated DataFrame:
    ID   Source  Severity          Start_Time             End_Time  Start_Lat  \
0  A-1  Source2         3 2016-02-08 05:46:00  2016-02-08 11:00:00  39.865147
1  A-2  Source2         2 2016-02-08 06:07:59  2016-02-08 06:37:59  39.928059
2  A-3  Source2         2 2016-02-08 06:49:27  2016-02-08 07:19:27  39.063148
3  A-4  Source2         3 2016-02-08 07:23:34  2016-02-08 07:53:34  39.747753
4  A-5  Source2         2 2016-02-08 07:39:07  2016-02-08 08:09:07  39.627781

   Start_Lng  Distance(mi)                                        Description  \
0 -84.058723          0.01  Right lane blocked due to accident on I-70 Eas...
1 -82.831184          0.01  Accident on Brice Rd at Tussing Rd. Expect del...
2 -84.032608          0.01  Accident on OH-32 State Route 32 Westbound at ...
3 -84.205582          0.01  Accident on I-75 Southbound at Exits 52 52B US...
4 -84.188354          0.01  Accident on McEwen Rd at OH-725 Miamisburg Cen...

           City State  Temperature(F) Weather_Condition  Amenity   Bump  \
0        Dayton    OH            36.9        Light Rain    False  False
1  Reynoldsburg    OH            37.9        Light Rain    False  False
2  Williamsburg    OH            36.0          Overcast    False  False
3        Dayton    OH            35.1     Mostly Cloudy    False  False
4        Dayton    OH            36.0     Mostly Cloudy    False  False

   Crossing  Traffic_Signal Sunrise_Sunset
0     False           False          Night
1     False           False          Night
2     False            True          Night
3     False           False          Night
4     False            True            Day

In [ ]:
import pandas as pd

from google.colab import drive
import pandas as pd
import os


# Mount Google Drive
drive.mount('/content/drive')

# Specify the path in Google Drive
drive_path = '/content/drive/MyDrive/DetyreKursi/us-accidents_silver.csv'

# Read the CSV file
dfff = pd.read_csv(drive_path)

dfff.info()

Mounted at /content/drive
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 18 columns):
 #   Column             Dtype
---  ------             -----
 0   ID                 object
 1   Source             object
 2   Severity           int64
 3   Start_Time         object
 4   End_Time           object
 5   Start_Lat          float64
 6   Start_Lng          float64
 7   Distance(mi)       float64
 8   Description        object
 9   City               object
 10  State              object
 11  Temperature(F)     float64
 12  Weather_Condition  object
 13  Amenity            bool
 14  Bump               bool
 15  Crossing           bool
 16  Traffic_Signal     bool
 17  Sunrise_Sunset     object
dtypes: bool(4), float64(4), int64(1), object(9)
memory usage: 855.0+ MB

In [ ]:

# konvertoj me force
dfff['Start_Time'] = pd.to_datetime(dfff['Start_Time'], errors='coerce')

# ruaj ndryshimet
dfff.to_csv(file_path, index=False)

In [ ]:
dfff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 18 columns):
 #   Column             Dtype
---  ------             -----
 0   ID                 object
 1   Source             object
 2   Severity           int64
 3   Start_Time         datetime64[ns]
 4   End_Time           object
 5   Start_Lat          float64
 6   Start_Lng          float64
 7   Distance(mi)       float64
 8   Description        object
 9   City               object
 10  State              object
 11  Temperature(F)     float64
 12  Weather_Condition  object
 13  Amenity            bool
 14  Bump               bool
 15  Crossing           bool
 16  Traffic_Signal     bool
 17  Sunrise_Sunset     object
dtypes: bool(4), datetime64[ns](1), float64(4), int64(1), object(8)
memory usage: 855.0+ MB

In [ ]:
drive_path = '/content'
# Convert 'Start_Time' and 'End_Time' to datetime format
df['Start_Time'] = pd.to_datetime(df['Start_Time'])
df['End_Time'] = pd.to_datetime(df['End_Time'])


# Mount Google Drive
drive.mount('/content/drive')

# Specify the path in Google Drive
drive_path = '/content/drive/MyDrive/DetyreKursi/'

# Create the directory if it doesn't exist
import os
os.makedirs(drive_path, exist_ok=True)

# Save the changes to a new CSV file
updated_file_path = drive_path + 'us-accidents_silver_updated.csv'
df.to_csv(updated_file_path, index=False)

# Display the head of the updated DataFrame
print("\nHead of the Updated DataFrame:")
print(df.head())

# Confirm that the changes have been saved successfully
print(f"\nThe updated silver table has been saved to: {updated_file_path}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Head of the Updated DataFrame:
    ID   Source  Severity          Start_Time            End_Time  Start_Lat  \
0  A-1  Source2         3 2016-02-08 05:46:00 2016-02-08 11:00:00  39.865147
1  A-2  Source2         2 2016-02-08 06:07:59 2016-02-08 06:37:59  39.928059
2  A-3  Source2         2 2016-02-08 06:49:27 2016-02-08 07:19:27  39.063148
3  A-4  Source2         3 2016-02-08 07:23:34 2016-02-08 07:53:34  39.747753
4  A-5  Source2         2 2016-02-08 07:39:07 2016-02-08 08:09:07  39.627781

   Start_Lng  Distance(mi)                                        Description  \
0 -84.058723          0.01  Right lane blocked due to accident on I-70 Eas...
1 -82.831184          0.01  Accident on Brice Rd at Tussing Rd. Expect del...
2 -84.032608          0.01  Accident on OH-32 State Route 32 Westbound at ...
3 -84.205582          0.01  Accident on I-75 Southbound at Exits 52 52B US...
4 -84.188354          0.01  Accident on McEwen Rd at OH-725 Miamisburg Cen...

           City State  Temperature(F) Weather_Condition  Amenity   Bump  \
0        Dayton    OH            36.9        Light Rain    False  False
1  Reynoldsburg    OH            37.9        Light Rain    False  False
2  Williamsburg    OH            36.0          Overcast    False  False
3        Dayton    OH            35.1     Mostly Cloudy    False  False
4        Dayton    OH            36.0     Mostly Cloudy    False  False

   Crossing  Traffic_Signal Sunrise_Sunset
0     False           False          Night
1     False           False          Night
2     False            True          Night
3     False           False          Night
4     False            True            Day

The updated silver table has been saved to: /content/drive/MyDrive/DetyreKursi/us-accidents_silver_updated.csv

In [ ]:
from google.colab import drive
import pandas as pd
import os


# Mount Google Drive
drive.mount('/content/drive')

# Specify the path in Google Drive
drive_path = '/content/drive/MyDrive/DetyreKursi/us-accidents_silver_updated.csv'

# Specify the chunk size (adjust according to your system's memory capacity)
chunk_size = 100000

# Initialize an empty list to store the chunks
chunks = []

# Read the CSV file in chunks and append them to the list
for chunk in pd.read_csv(drive_path,chunksize=chunk_size):
    chunks.append(chunk)

# Concatenate all the chunks into a single DataFrame
df = pd.concat(chunks)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Description,City,State,Temperature(F),Weather_Condition,Amenity,Bump,Crossing,Traffic_Signal,Sunrise_Sunset
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,0.01,Right lane blocked due to accident on I-70 Eas...,Dayton,OH,36.9,Light Rain,False,False,False,False,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,0.01,Accident on Brice Rd at Tussing Rd. Expect del...,Reynoldsburg,OH,37.9,Light Rain,False,False,False,False,Night
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,0.01,Accident on OH-32 State Route 32 Westbound at ...,Williamsburg,OH,36.0,Overcast,False,False,False,True,Night
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,0.01,Accident on I-75 Southbound at Exits 52 52B US...,Dayton,OH,35.1,Mostly Cloudy,False,False,False,False,Night
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,0.01,Accident on McEwen Rd at OH-725 Miamisburg Cen...,Dayton,OH,36.0,Mostly Cloudy,False,False,False,True,Day

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 18 columns):
 #   Column             Dtype
---  ------             -----
 0   ID                 object
 1   Source             object
 2   Severity           int64
 3   Start_Time         object
 4   End_Time           object
 5   Start_Lat          float64
 6   Start_Lng          float64
 7   Distance(mi)       float64
 8   Description        object
 9   City               object
 10  State              object
 11  Temperature(F)     float64
 12  Weather_Condition  object
 13  Amenity            bool
 14  Bump               bool
 15  Crossing           bool
 16  Traffic_Signal     bool
 17  Sunrise_Sunset     object
dtypes: bool(4), float64(4), int64(1), object(9)
memory usage: 855.0+ MB

In [ ]:
import pandas as pd
from google.colab import drive
import os


# Mount Google Drive
drive.mount('/content/drive')

# Specify the file path
file_path = '/content/drive/MyDrive/DetyreKursi/us-accidents_silver.csv'

# Read the CSV file into a DataFrame
df1 = pd.read_csv(file_path)

# Convert 'Start_Time' and 'End_Time' to datetime format
df1['Start_Time'] = pd.to_datetime(df1['Start_Time'])
df1['End_Time'] = pd.to_datetime(df1['End_Time'])

# Mount Google Drive
drive.mount('/content/drive')

# Specify the path in Google Drive
drive_path = '/content/drive/MyDrive/DetyreKursi/'

# Create the directory if it doesn't exist
import os
os.makedirs(drive_path, exist_ok=True)

# Save the changes to the same CSV file
df1.to_csv(file_path, index=False)

# Display the head of the updated DataFrame
print("\nHead of the Updated DataFrame:")
print(df1.head())

# Confirm that the changes have been saved successfully
print(f"\nThe updated silver table has been saved to: {file_path}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Head of the Updated DataFrame:
    ID   Source  Severity          Start_Time            End_Time  Start_Lat  \
0  A-1  Source2         3 2016-02-08 05:46:00 2016-02-08 11:00:00  39.865147
1  A-2  Source2         2 2016-02-08 06:07:59 2016-02-08 06:37:59  39.928059
2  A-3  Source2         2 2016-02-08 06:49:27 2016-02-08 07:19:27  39.063148
3  A-4  Source2         3 2016-02-08 07:23:34 2016-02-08 07:53:34  39.747753
4  A-5  Source2         2 2016-02-08 07:39:07 2016-02-08 08:09:07  39.627781

   Start_Lng  Distance(mi)                                        Description  \
0 -84.058723          0.01  Right lane blocked due to accident on I-70 Eas...
1 -82.831184          0.01  Accident on Brice Rd at Tussing Rd. Expect del...
2 -84.032608          0.01  Accident on OH-32 State Route 32 Westbound at ...
3 -84.205582          0.01  Accident on I-75 Southbound at Exits 52 52B US...
4 -84.188354          0.01  Accident on McEwen Rd at OH-725 Miamisburg Cen...

           City State  Temperature(F) Weather_Condition  Amenity   Bump  \
0        Dayton    OH            36.9        Light Rain    False  False
1  Reynoldsburg    OH            37.9        Light Rain    False  False
2  Williamsburg    OH            36.0          Overcast    False  False
3        Dayton    OH            35.1     Mostly Cloudy    False  False
4        Dayton    OH            36.0     Mostly Cloudy    False  False

   Crossing  Traffic_Signal Sunrise_Sunset
0     False           False          Night
1     False           False          Night
2     False            True          Night
3     False           False          Night
4     False            True            Day

The updated silver table has been saved to: /content/drive/MyDrive/DetyreKursi/us-accidents_silver.csv

In [ ]:
import pandas as pd
from google.colab import drive
import os


# Mount Google Drive
drive.mount('/content/drive')

# Specify the file path
file_path = '/content/drive/MyDrive/DetyreKursi/us-accidents_silver.csv'

# Read the CSV file into a DataFrame
df1 = pd.read_csv(file_path)


# Notebook 1:
df1 = pd.read_csv(file_path)
df1['Start_Time'] = pd.to_datetime(df1['Start_Time'])
df1['End_Time'] = pd.to_datetime(df1['End_Time'])
df1.to_csv(file_path, index=False)  # Save changes to file

Mounted at /content/drive

In [ ]:
import pandas as pd
from google.colab import drive

# Specify the file path
file_path = '/content/drive/MyDrive/DetyreKursi/us-accidents_silver.csv'

# Read the CSV file into a DataFrame and set data types
df2 = pd.read_csv(file_path, parse_dates=['Start_Time', 'End_Time'])

# Display the data types of 'Start_Time' and 'End_Time' in the current DataFrame
print("Data Types in the Current Notebook:")
print(df2[['Start_Time', 'End_Time']].dtypes)

# Re-save the file with explicit data types
df2.to_csv(file_path, index=False, date_format='%Y-%m-%d %H:%M:%S')

# Confirm the last modified time of the file
import os
print("\nLast Modified Time of the File:")
print(os.path.getmtime(file_path))

# Download the saved CSV file and open it in a local environment
# This step is for verification in a local environment, not necessary for the notebook
# Use a tool like Pandas in a Jupyter notebook or any other CSV reader

Data Types in the Current Notebook:
Start_Time    datetime64[ns]
End_Time      datetime64[ns]
dtype: object

Last Modified Time of the File:
1704134945.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 18 columns):
 #   Column             Dtype
---  ------             -----
 0   ID                 object
 1   Source             object
 2   Severity           int64
 3   Start_Time         datetime64[ns]
 4   End_Time           object
 5   Start_Lat          float64
 6   Start_Lng          float64
 7   Distance(mi)       float64
 8   Description        object
 9   City               object
 10  State              object
 11  Temperature(F)     float64
 12  Weather_Condition  object
 13  Amenity            bool
 14  Bump               bool
 15  Crossing           bool
 16  Traffic_Signal     bool
 17  Sunrise_Sunset     object
dtypes: bool(4), datetime64[ns](1), float64(4), int64(1), object(8)
memory usage: 855.0+ MB